suppressPackageStartupMessages(library('argparse'))
suppressPackageStartupMessages(library('ape'))
suppressPackageStartupMessages(library('phytools'))

parser <- ArgumentParser()

parser$add_argument("-t", "-tree",  
    dest="t", help="The tree file generated by syngraph (newick; nodes requre nXX labels).")
parser$add_argument("-n", "-nodes_dir",  dest="nodes_dir",
    help="The name of the directory with states in all nodes generated by decompose_table.py script.")
### for per-ALG stats
parser$add_argument("-a", "-algs", default = "",
    help="The name of the ALG definitions to be used (tsv file, potentially generated using define_ALGs.R script).")
parser$add_argument("-o", "-output",  
    dest="o", help="Base of the output name (.png will be attached)")

args <- parser$parse_args()

# these need to be made into arguments in the end
treefile <- args$t 
# treefile <- 'data/hymenoptera/syngraph_run_pruned2/hymenoptera.mindist.m50.syngraph_infer.newick.txt'
busco_asn_file <- args$a
# busco_asn_file <- 'data/hymenoptera/syngraph_run/ALG_syngraph.hymenoptera.n4.ALGs.tsv' # args$a
directory_with_nodes <- args$nodes_dir
# directory_with_nodes <- paste0("data/hymenoptera/syngraph_run_pruned2/node_asn/")

output_figure <- paste0(args$o, '.pdf')

### LOADING FILES

## node files
all_node_files <- dir(directory_with_nodes, pattern = '^n[0-9]+_seq.tsv$')
node_names <- sapply(strsplit(all_node_files, "_"), function(x){x[1]} )
busco_order <- read.table(paste0(directory_with_nodes, 'busco_order.tsv'), header = F, col.names = c('busco'))[, 1]

if ( busco_asn_file != ""){
    ALG_data <- read.table(busco_asn_file, col.names = c('busco', 'chrQ'))
}


# ########## Loading states at all the nodes
# # testing: input_file <- paste0("data/syngraph/node_assignments/", all_node_files[1])
load_node <- function(node_file){
    # print(paste("Processing", node_file))
    # node_file <- 'data/hymenoptera/syngraph_run/node_asn/n12_seq.tsv'
    # node_file <- 'data/hymenoptera/syngraph_run/node_asn/n100_seq.tsv' 
    # test <- read.table('data/hymenoptera/syngraph_run/node_asn/n12_seq.tsv', blank.lines.skip=F
    node_lgs <- read.table(node_file, header = F, blank.lines.skip = F, col.names = c('chrNode'))
    if (all(is.na(node_lgs[, 1]))){
        return(data.frame(ALG=character(), node=character(), Count=integer()))
    }
    node_lgs <- data.frame(busco = busco_order, chrNode = node_lgs[, 1])
    node_lgs <- node_lgs[node_lgs[, 'chrNode'] != "", ]
    # needs ALG_data
    if ( busco_asn_file != ""){
        node_lgs_by_algs <- merge(ALG_data, node_lgs)
        
    } else {
        node_lgs_by_algs <- node_lgs
        node_lgs_by_algs[, 'chrQ'] <- ""
    }
    dat <- data.frame(table(node_lgs_by_algs$chrQ,node_lgs_by_algs$chrNode))

    names(dat) <- c("ALG","node","Count")
    return(dat)
}

all_node_asn <- lapply(paste0(directory_with_nodes, all_node_files), load_node)
names(all_node_asn) <- node_names

buscos_per_node <- sapply(all_node_asn, function(x){ sum(x[, 3]) } )

## tree processing

tree <- read.tree(treefile)
tree_components <- c(tree$tip.label, tree$node.label)
number_of_tips <- length(tree$tip.label)
nodei_range <- (number_of_tips + 2):length(tree_components)

### CONSTRUCTING PER NODE TABLE
node_tab <- data.frame(node = tree_components[nodei_range], 
                       descendants = sapply(nodei_range, function(x){ sum(getDescendants(tree, x) <= number_of_tips) }))

descendants_i <- t(sapply(nodei_range, function(node_i){ tree$edge[which(tree$edge[, 1] == node_i), 2] }))

node_tab[, 'desc_1'] <- tree_components[descendants_i[, 1]]
node_tab[, 'desc_2'] <- tree_components[descendants_i[, 2]]

node_tab[, 'markers'] <- buscos_per_node[node_tab[, 1]]

plot(node_tab[, 'markers'] ~ node_tab[, 'descendants'])

rownames(node_tab) <- node_tab[, 1]

# node_tab[order(node_tab[,'descendants']), ]

##### plot

pdf(output_figure)

plot(node_tab[, 'markers'] ~ node_tab[, 'descendants'], pch = 20, xlab = 'Number of descendant tips', ylab = 'Number of BUSCO markers')
for ( node in 1:nrow(node_tab)){
    parent_x <- node_tab[node, 'descendants']
    parent_y <- node_tab[node, 'markers']

    offspring_x <- node_tab[node_tab[node, 'desc_1'], 'descendants']
    offspring_y <- node_tab[node_tab[node, 'desc_1'], 'markers']

    lines(c(parent_x, offspring_x), c(parent_y, offspring_y))

    offspring_x <- node_tab[node_tab[node, 'desc_2'], 'descendants']
    offspring_y <- node_tab[node_tab[node, 'desc_2'], 'markers']

    lines(c(parent_x, offspring_x), c(parent_y, offspring_y))
}

options(width = 120)

dev.off()

head(node_tab[order(node_tab[, 'markers'], node_tab[, 'descendants']), c(-1)], 30)
# this is the most helpful!

## ALGs

