suppressPackageStartupMessages(library('argparse'))
suppressPackageStartupMessages(library('ape'))
suppressPackageStartupMessages(library('phytools'))
# suppressPackageStartupMessages(library('gsheet'))
# suppressPackageStartupMessages(library(ggplot2))

# parser <- ArgumentParser()

parser <- ArgumentParser()

parser$add_argument("-a", "-algs", 
    help="The name of the ALG definitions to be used (tsv file, potentially generated using define_ALGs.R script).")
parser$add_argument("-n", "-nodes_dir",  dest="nodes_dir",
    help="The name of the directory with states in all nodes generated by decompose_table.py script.")

parser$add_argument("-s", "-species_table", 
    dest="species_table", help="A tsv with species and taxonomy - file requires 'species' in the header and accepts any taxonomic ranks; requires specified taxonomic rank by -level argument.", default = "")
parser$add_argument("-l", "-level",  
    dest="l", help="Taxonomic level to plot (present in the header or -species_table)", default = "family")
parser$add_argument("-subtree",  
    dest="subtree", help="Plot only a subtree from a specified node.", default = "")

parser$add_argument("-t", "-tree",  
    dest="t", help="The tree file generated by syngraph (newick; nodes requre nXX labels).")
parser$add_argument("-r", "-rearrangements", default = '', 
    dest="r", help="The table with rearrangements at nodes (output of syngraph). If not specified, all nodes will be plotted irrespective of kartypic change.")

parser$add_argument("-o", "-output",  
    dest="o", help="Base of the output name (.png will be attached)")

args <- parser$parse_args()

source('scripts/ALGs_palettes.R') # can be argumented somehow?

# these need to be made into arguments in the end
treefile <- args$t 
# treefile <- 'data/hymenoptera/syngraph_run/hymenoptera.mindist.m50.newick.txt'
rearrangement_file <- args$r
# rearrangement_file <- 'data/hymenoptera/syngraph_run/hymenoptera.mindist.m50.rearrangements.tsv'

taxonomy_file <- args$species_table
# taxonomy_file <- 'data/hymenoptera/Hymenoptera_genomes_taxonomy.tsv'
plot_level <- args$l
# plot_level <- 'family'
subtree <- args$subtree

busco_asn_file <- args$a
# busco_asn_file <- 'data/hymenoptera/syngraph_run/ALG_syngraph.hymenoptera.n4.ALGs.tsv' # args$a
directory_with_nodes <- args$nodes_dir
# directory_with_nodes <- paste0("data/hymenoptera/syngraph_run/node_asn/")

output_tree <- paste0(args$o, '.pdf')

# Rscript scripts/plot_tree_with_ALGs_at_nodes.R -t data/hymenoptera/syngraph_run/hymenoptera.mindist.m50.newick.txt -a data/hymenoptera/syngraph_run/ALG_syngraph.hymenoptera.n4.ALGs.tsv -n data/hymenoptera/syngraph_run/node_asn/ -r data/hymenoptera/syngraph_run/hymenoptera.mindist.m50.rearrangements.tsv -o figures/syngraph_tree_of_changes

#########################################################################
############# VARIABLES ################
#########################################################################
# simplified; if 0 means not simplified, if a number it is the number of pieces it gets simplfied to
simplified <- 0

all_node_files <- dir(directory_with_nodes, pattern = '^n[0-9]+_seq.tsv$')
node_names <- sapply(strsplit(all_node_files, "_"), function(x){x[1]} )
busco_order <- read.table(paste0(directory_with_nodes, 'busco_order.tsv'), header = F, col.names = c('busco'))[, 1]

ALG_data <- read.table(busco_asn_file, col.names = c('busco', 'chrQ'))

# ########## Loading states at all the nodes
# # testing: input_file <- paste0("data/syngraph/node_assignments/", all_node_files[1])
load_node <- function(node_file){
    # print(paste("Processing", node_file))
    # node_file <- 'data/hymenoptera/syngraph_run/node_asn/n12_seq.tsv'
    # node_file <- 'data/hymenoptera/syngraph_run/node_asn/n100_seq.tsv' 
    # test <- read.table('data/hymenoptera/syngraph_run/node_asn/n12_seq.tsv', blank.lines.skip=F
    node_lgs <- read.table(node_file, header = F, blank.lines.skip = F, col.names = c('chrNode'))
    if (all(is.na(node_lgs[, 1]))){
        return(data.frame(ALG=character(), node=character(), Count=integer()))
    }
    node_lgs <- data.frame(busco = busco_order, chrNode = node_lgs[, 1])
    node_lgs <- node_lgs[node_lgs[, 'chrNode'] != "", ]
    # needs ALG_data
    node_lgs_by_algs <- merge(ALG_data, node_lgs)
    dat <- data.frame(table(node_lgs_by_algs$chrQ,node_lgs_by_algs$chrNode))
    names(dat) <- c("ALG","node","Count")
    return(dat)
}

all_node_asn <- lapply(paste0(directory_with_nodes, all_node_files), load_node)
names(all_node_asn) <- node_names
# all_node_asn is a list node -> busco assignments gruped by assigments

######### Processing rearrangement file

if ( rearrangement_file != "" ){
    print(paste('Loading', rearrangement_file, "will be plotting rearranging nodes only."))
    all_rearrangements <- read.table(rearrangement_file, sep = '\t')
    nodes_with_changes <- list()
    ## every line is a chromosomal rearrangement, and second column is the name of the node/tip when the rearrangement happened
    ## table of the names gives a list of changes per node
    nodes_with_changes[names(table(all_rearrangements[, 2]))] <- TRUE
    ## nodes that are NOT changing are not in the list
} else {
    print("No rearrangement file: plotting all nodes.")
}

# if(is.null(nodes_with_changes[['n84']])){ print('well hellp')}
# is.null(nodes_with_changes[['n583']])

# ######### Loading tree
tree <- read.tree(treefile)
# # rooted_tree <- tree # root(tree, "Panorpa_germanica", resolve.root = T)
if ( subtree != "" ){
    subtree_node <- which(tree$node.label == subtree) + length(tree$tip.label)
    tree <- extract.clade(tree, subtree_node)
}

tree_components <- c(tree$tip.label, tree$node.label)

# ######### Processing

if ( taxonomy_file != "" ){
    taxonomy <- read.table(taxonomy_file, header = T, sep = '\t')

    if ( plot_level %in% colnames(taxonomy)){
        tax2species <- aggregate(taxonomy[, 'species'], list(taxonomy[, plot_level]), c)

    } else if (plot_level == 'genus'){
        print('Genus not specified in the table - proceeding with the first word of species name')
        genera <- sapply(strsplit(taxonomy[, 'species'], '_'), function(x){x[1]})
        tax2species <- aggregate(taxonomy[, 'species'], list(genera), c)

    } else {
        stop(paste('The taxonomy rank (-level)', plot_level, 'not in the header of the (-species_table) file: ', taxonomy_file))
    }

    tax2species <- tax2species[tax2species[, 1] != '', ] # removing if there is "empty taxon" (species with no taxon specified)
    tax2node <- list()
    tax2descendants <- list()

    for (tax_i in 1:nrow(tax2species)){
        tax <- tax2species[tax_i, 1]
        species <- unlist(tax2species[tax_i, 2])

        # keep only the species in the tree
        species <- species[species %in% tree$tip.label]

        if (length(species) > 1){
            mrca <- getMRCA(tree, species)
            tax2node[[tax]] <- tree_components[mrca]
            tax2descendants[[tax]] <- tree_components[getDescendants(tree, mrca, curr=NULL)]
        }
    }
    nodes_to_avoid <- unique(unlist(tax2descendants))

} else {
    "No species_table with taxonomy provided, plotting all taxonomic ranks."
    nodes_to_avoid <- c()
}

########## Plotting the tree

pdf(output_tree, height = 60, width = 20)

plot(tree,  show.node.label = TRUE)

lastPP <- get("last_plot.phylo", envir = .PlotPhyloEnv)

chwidth <- max(lastPP$x.lim) / 100
chheight <- 2
chgap <- max(lastPP$x.lim) / 400
y_smallstep <- 0.04

# indices of nodes are after the tree components corresponding to the tips
for (node_i in c(length(tree$tip.label) + 2):length(lastPP$xx)){
    node <- tree_components[node_i]
    # print(paste("Processing", node, "."))    

    if ( rearrangement_file != "" ){
        if ( is.null(nodes_with_changes[[node]]) ){
            # print(paste("Skipping", node, " - no changes."))
            next
        }
    }

    if ( node %in% nodes_to_avoid){
        # print(paste("Skipping", node, " - sub-", plot_level, "level."))
        next
    }

    if ( ! node %in% names(all_node_asn) ){
        print(paste("Skipping", node, " - not among nodes."))
        next
    }

    print(paste("Plotting", node, "-", plot_level, "level or above."))
#     if ( node %in% unlist(family2node) ){
#         print(paste("Skipping", node, " - Family node."))
#         next
#     }
    node_asn <- all_node_asn[[node]]
    # print(node)
    # print(head(node_asn))
    # print( node %in% names(all_node_asn))

    x <- lastPP$xx[node_i]
    y <- lastPP$yy[node_i]
    yfrom <- y + y_smallstep
    yto <- y + y_smallstep + chheight
    # rect(x - (5 * (chwidth + chgap)), yfrom, x, yto, col = 'red') # - this is to test without actual painitng.

    if (nrow(node_asn) == 0){
        print(paste("Red box at", node, " - failed inference."))
        rect(x - chwidth - chgap, yfrom, x - chgap, yto, col = 'red')
        next        
    }

    # get order right 
    lgs_to_plot <- levels(node_asn[, 'node'])
    mixed <- 0
    all_node_lgs <- unique(node_asn[, 2])
    dominan_asn <- sapply(all_node_lgs, function(x){ chr_subset = node_asn[node_asn[, 2] == x, ]; chr_subset[which.max(chr_subset[, 'Count']), 1]})
    ordered_lgs <- all_node_lgs[order(dominan_asn, decreasing = T)]
    lgs_to_plot <- ordered_lgs
    ##

    for (chr in 1:length(lgs_to_plot)){
        xfrom <- x - (chr * (chwidth + chgap))
        xto <- x - ((chr - 1) * (chwidth + chgap) + chgap)

        bar_subset <- node_asn[node_asn[, 'node'] == lgs_to_plot[chr], ]
        # making sure the order in the plot will be consisent
        bar_subset <- bar_subset[order(bar_subset[, 'ALG'], decreasing = F), ]
        if (simplified == 0){
            columns_to_plot <- y + y_smallstep + (chheight * c(0, cumsum(bar_subset[, "Count"])) / sum(bar_subset[, "Count"]))
        } else {
            theshold <- 1 / simplified
            pieces_per_ALG <- round((bar_subset[, "Count"] / sum(bar_subset[, "Count"])) / theshold)
            mixed <- (simplified - sum(pieces_per_ALG))
            columns_to_plot <- y + y_smallstep + (chheight * c(0, cumsum(pieces_per_ALG)) / simplified)
        }

        for(i in 1:nrow(bar_subset)){
            if ( columns_to_plot[i] != columns_to_plot[i + 1]){
                rect(xfrom, columns_to_plot[i], 
                    xto, columns_to_plot[i + 1], 
                    col = pal[as.character(bar_subset[i, 'ALG'])], border = NA)
            }
        }
        if (mixed != 0){
            rect(xfrom, columns_to_plot[i + 1], 
                xto, yto, 
                col = 'gray', border = NA)            
        }
    }
}

dev.off()

# familes_to_plot <- rev(read.table('tables/families_ordered_by_tree.tsv')[, 1])

# familes_to_plot <- names(family2node)
# algs_per_family <- sapply(family2node, function(x){length(unique(all_node_asn[[x]][, 'node']))})
# max_nodes_to_plot <- max(algs_per_family)
# barwidth <- 0.45

# pdf('figures/family_paints.pdf', height = 60, width = 10)

# plot(NA, xlim = c(-1, max_nodes_to_plot + barwidth), ylim = c(0, length(familes_to_plot)), bty = 'n', axes = F, xlab = '', ylab = '')

# for (rowi in 1:length(familes_to_plot)){
#     ybaseline <- rowi - 1
#     family <- familes_to_plot[rowi]

#     text(-0.5, ybaseline, family, pos = 3)

#     family_node <- family2node[[family]]
#     if ( is.null(family_node) ){
#         print(paste("Skipping", family, " - not in the syngraph tree"))
#         next
#     }
#     dat <- all_node_asn[[family_node]]
#     if ( is.null(dat) ) {
#         print(paste("Skipping", family, " - lacking family node reconstruction"))
#     }

#     nodes_to_plot <- levels(dat[, 'node'])
#     dominan_asn <- sapply(nodes_to_plot, function(x){ chr_subset = dat[dat[, 2] == x, ]; chr_subset[which.max(chr_subset[, 'Count']), 1]})
#     ordered_lgs <- nodes_to_plot[order(dominan_asn, decreasing = T)]
#     nodes_to_plot <- rev(ordered_lgs)

#     for (node in 1:length(nodes_to_plot)){
#         xpos <- node
#         bar_subset <- dat[dat[, 'node'] == nodes_to_plot[node], ]
#         # making sure the order in the plot will be consisent
#         bar_subset <- bar_subset[order(bar_subset[, 'ALG'], decreasing = F), ]
#         columns_to_plot <- c(0, cumsum(bar_subset[, "Count"])) / sum(bar_subset[, "Count"]) * 0.8

#         for(i in 1:nrow(bar_subset)){
#             rect(xpos - barwidth, ybaseline + columns_to_plot[i], 
#                 xpos + barwidth, ybaseline + columns_to_plot[i + 1], 
#                 col = pal[as.character(bar_subset[i, 'ALG'])], border = NA)
#         }
#     }
# }

# dev.off()